config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :pins

	root 'pins#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user

	has_attached_file :image, styles:{medium: "300x300>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pins
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show,:edit,:update,:destroy]
	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def show
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Novo Pin criado com sucesso"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin foi atualizado"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end


	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='nav navbar navbar-default' >
      <div class='container'>
        <div class='navbar-brand'>
          <%= link_to 'Pin Board', root_path %>
        </div>
        <ul class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>  
            <li><%= link_to 'New Pin', new_pin_path %></li>
            <li><%= link_to 'Account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          </ul>
        <% end %>
      </div>
    </div>
    <div class='container'>
        <%= yield %>
    </div>
  </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: {multipart: true} do |f| %>
	<% if @pin.errors.any? %>
		<div id='erro_explnation'>
			<h2>
				<%= pluralize(@pin.errors.count, 'error') %>
				prevented this Pin from saving
			</h2>
			<ul>
				<% @pin.error.full_messages.each do |msg| %>
				<li>msg</li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class='form-group'>
		<p><%= f.input :image, input_html: {class:'form-control'} %></p>
		<p><%= f.input :title, input_html: {class:'form-control'} %></p>
		<p><%= f.input :description, input_html: {class:'form-control'} %></p>
		<p><%= f.button :submit, class: 'btn btn-primary' %></p>
	</div>
<% end %>

app/views/pins/edit.html.erb
<div class ='col-md-6 col-md-offset-3'
	<h1> Edit Pin </h1>
	<%= image_tag @pin.image.url(:medium) %>
	<%= render 'form' %>
	<%= link_to 'Cancel', pin_path %>
</div>

app/views/pins/index.html.erb
<% @pins.each do |pin| %>
	<%= link_to (image_tag pin.image.url(:medium)), pin %>
	<h2><%= link_to pin.title, pin %></h2>
<% end %>

app/views/pins/new.html.erb
<div class ='col-md-6 col-md-offset-3'
	<h1>New form</h1>
	<%= render 'form' %>
	<%= link_to 'Back', root_path %>
</div>

app/views/pins/show.html.erb
<%= image_tag @pin.image.url(:medium) %>
<h1><%= @pin.title %></h1>
<p><%= @pin.description %></p>
<p>Submitted By @<%= @pin.user.email %></p>

<%= link_to 'Back', root_path %>
<%= link_to 'Edit', edit_pin_path %>
<%= link_to 'Delete', pin_path, method: :delete, data: {confirm: 'Are you sure?'} %>